# Generated by Django 4.1.5 on 2023-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='partner_offer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
